# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 765470d282f22cffa3cf501395da05fc3f742a0b00e4bf4628de3ef5e07cc95fdec78685328406d60a237bc1cafbfd98246721c2354d233387b0544856a5c681

test:
  secret_key_base: c8eb2821133031a4b47280931b7f5c87524bc721c43ac5f52dc8423308cd6177c56ae36d62acee9206c4d9f138e189f60d8b037984cbe43845c3c2c9ff6f0a5f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
